### PR TITLE
Adding partial bathymetry tutorial to test git workflow

### PR DESCRIPTION
**Pull request by jonm3D**
Not intended for publication, just working through the example from the Zoom call.

### CODE REVIEW

**Review by scottyhq — CHANGES_REQUESTED** [review]
Thanks @jonm3D ! You'll notice the QualityWorkflow Ensure Clean Notebook failed, you'll want to commit your notebook with only inputs: In JupyterLab: `restart kernel and clear all outputs`.

**Comment by jonm3D** [comment]
Thanks for your help Scott, just pushed with the cell output cleared. I'm not sure, but it looks like an interactive part of my demo so far (where users can draw a bounding box to use for querying Sliderule) seems to be causing issues.

**Comment by scottyhq** [comment]
> it looks like an interactive part of my demo so far (where users can draw a bounding box to use for querying Sliderule) seems to be causing issues. 

Indeed, there are two options.

1. I think the easiest solution is to have a cell above that sets a default `bbox_coords` such that the following cells will still execute. 

2. Alternatively, you can go back to keeping the outputs and skip executing this notebook entirely with this setting

https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/943033ba69ed090405ad4f214b188e1539cf396d/book/_config.yml#L39-L40

**Comment by scottyhq** [comment]
@jonm3D the table of contents sometimes needs adjusting when other tutorials get merged in. i just added a commit to to that. This looks close to being ready to merge in?

**Comment by scottyhq** [comment]
@jonm3D there is a very unhelpful build error `/home/runner/work/ICESat-2-Hackweek-2023/ICESat-2-Hackweek-2023/book/tutorials/bathymetry/bathymetry_tutorial.ipynb:10019: WARNING: 'myst' reference target not found: `

which is coming from your empty markdown links:
`[density-based](), [histogram-based]()`

Also note spellchecker errors https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/actions/runs/5767172202/job/15636427945?pr=40

If you have a change please fix those and I'll merge this in! The plots are fantastic

**Review by scottyhq — APPROVED** [review]

**Comment by jonm3D** [comment]
Thanks Scott for your help!

**Pull request merged**
