### PR TITLE
Update netlifypreview.yaml

### LINKED ISSUE #52: Create Netlify Preview even if build step raises an error
This PR didn't get a preview https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/pull/50

Simply because `WARNING: Non-consecutive header level increase; 2 to 4 [myst.header]` raises an error code 

https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/c602d216138c08ea748e8248786b438985752696/scripts/build_resources.sh#L39

Log:
https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/actions/runs/5720017208/job/15499143677?pr=50

I think we want the warnings to still raise errors, but at least create the preview link.

### PR DESCRIPTION
**Pull request by scottyhq**
Fixes #52

### CODE REVIEW

**Comment by jomey** [comment]
I feel that deploying a half build book won’t do the PR review any good and would be fine with the preview not deploying. It’s most likely the change under review that triggered an error when building.

Or am I missing a use case?

**Comment by scottyhq** [comment]
> I feel that deploying a half build book won’t do the PR review any good 

I think more often than not it would be deploying 98% of the book due to the `--keep-going` flag
https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/c602d216138c08ea748e8248786b438985752696/scripts/build_resources.sh#L39

> Or am I missing a use case?

The use case is mainly that I find reviewing the PR as a preview convenient :) And I think it can help diagnose issues such as missing pages, strange formatting, etc. 


But I see your point that the workflow should still 'Fail'. I think what I'm after is just to always run the preview comment step (`if: always()`) so that the preview URL is always there even if the workflow fails. Thoughts?

https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/c602d216138c08ea748e8248786b438985752696/.github/workflows/netlifypreview.yaml#L35-L37

**Comment by jomey** [comment]
Thanks for laying out the use case for me ;-)

Want to test this improvement by triggering an error of the build and adding the ‘preview’ label? Maybe use the inconsistent headings in a notebook?

**Review by jomey — APPROVED** [review]

**Comment by scottyhq** [comment]
> Want to test this improvement by triggering an error of the build and adding the ‘preview’ label? Maybe use the inconsistent headings in a notebook? 

I quickly tried this, but because it is a `pull_request_target` workflow it runs the version of the yml on the `main` branch. So we'll have to merge and fix later if it doesn't work as expected.

**Pull request merged**
